/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.proyectoinventarioproduct.app;

import com.mycompany.proyectoinventarioproduct.dao.inventarioDao;
import com.mycompany.proyectoinventarioproduct.models.Lista;
import com.mysql.cj.util.StringUtils;
import java.util.ArrayList;
import java.util.List;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author diegovidelasilva
 */
public class Aplicacion extends javax.swing.JFrame {
    
    private List<Lista> lista = new ArrayList<>();

    /**
     * Creates new form Aplicacion
     */
    public Aplicacion() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
 
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jScrollPane1 = new javax.swing.JScrollPane();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();
        labelProducto = new javax.swing.JLabel();
        inputProducto = new javax.swing.JTextField();
        jScrollPane4 = new javax.swing.JScrollPane();
        outputList = new javax.swing.JList<>();
        btnEliminar = new javax.swing.JButton();
        labelMarca = new javax.swing.JLabel();
        inputMarca = new javax.swing.JTextField();
        labelUbicacion = new javax.swing.JLabel();
        inputUbicacion = new javax.swing.JTextField();
        labelCodigo = new javax.swing.JLabel();
        inputCodigo = new javax.swing.JTextField();
        labelDescripcion = new javax.swing.JLabel();
        inputDescripcion = new javax.swing.JTextField();
        labelCantidad = new javax.swing.JLabel();
        inputCantidad = new javax.swing.JTextField();
        labelInventario = new javax.swing.JLabel();
        btnEditar = new javax.swing.JButton();
        labelId = new javax.swing.JLabel();
        btnNuevo = new javax.swing.JButton();

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane2.setViewportView(jTextArea1);

        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jScrollPane3.setViewportView(jTextArea2);

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Inventario de Productos");
        setBackground(new java.awt.Color(102, 102, 102));
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });

        btnGuardar.setText("GUARDAR");
        btnGuardar.setToolTipText("");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        labelProducto.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        labelProducto.setText("PRODUCTO");

        inputProducto.setColumns(1);

        outputList.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        jScrollPane4.setViewportView(outputList);

        btnEliminar.setText("ELIMINAR");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        labelMarca.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        labelMarca.setText("MARCA");

        inputMarca.setColumns(1);

        labelUbicacion.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        labelUbicacion.setText("UBICACION");

        inputUbicacion.setColumns(1);

        labelCodigo.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        labelCodigo.setText("CODIGO");
        labelCodigo.setToolTipText("");

        inputCodigo.setColumns(1);
        inputCodigo.setToolTipText("");

        labelDescripcion.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        labelDescripcion.setText("DESCRIPCION");

        inputDescripcion.setColumns(1);

        labelCantidad.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        labelCantidad.setText("CANTIDAD");

        inputCantidad.setColumns(1);

        labelInventario.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        labelInventario.setText("INVENTARIO DE PRODUCTOS");

        btnEditar.setText("EDITAR");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });

        labelId.setForeground(new java.awt.Color(242, 242, 242));

        btnNuevo.setText("NUEVO");
        btnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addComponent(btnEliminar)
                        .addGap(18, 18, 18)
                        .addComponent(btnEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(btnNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 475, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelInventario)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(labelCantidad)
                                    .addComponent(labelCodigo)
                                    .addComponent(labelProducto)
                                    .addComponent(labelMarca))
                                .addGap(34, 34, 34)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(inputMarca, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(inputCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                            .addComponent(btnGuardar)
                                            .addGap(12, 12, 12))
                                        .addComponent(inputProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(inputDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(labelUbicacion)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(inputCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(labelDescripcion)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(inputUbicacion, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addContainerGap(80, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(labelId)
                        .addGap(107, 107, 107))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addComponent(labelId))
                            .addComponent(labelInventario, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(37, 37, 37)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(inputCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelCantidad))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(inputProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelCodigo))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(labelProducto)
                            .addComponent(inputMarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelMarca)
                            .addComponent(inputDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelDescripcion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(inputUbicacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelUbicacion)
                            .addComponent(inputCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(69, 69, 69))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 346, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(45, 45, 45)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEditar)
                    .addComponent(btnNuevo)
                    .addComponent(btnGuardar)
                    .addComponent(btnEliminar))
                .addContainerGap(29, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

////////////////////////////////////////////////////////////////////////////////////////////////// 
//////////////////////////////////////////////////////////////////////////////////////////////////    
    
    


//---------------------FUNCION BOTON GUARDAR----------------------------------//
    
    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
               
        Lista elemento = new Lista();                                   // Crear una variable "a" que trae datos del archivo Lista
        elemento.setCodigo(this.inputCodigo.getText().toUpperCase());               // esta variable a guarda los que se ingrese en el input de codigo
        elemento.setProducto(this.inputProducto.getText().toUpperCase());             // esta variable a guarda los que se ingrese en el input de producto
        elemento.setMarca(this.inputMarca.getText().toUpperCase());       // esta variable a guarda los que se ingrese en el input de marca
        elemento.setDescripcion(this.inputDescripcion.getText().toUpperCase());       // esta variable a guarda los que se ingrese en el input de descripcion
        elemento.setUbicacion(this.inputUbicacion.getText().toUpperCase());       // esta variable a guarda los que se ingrese en el input de ubicacion
        elemento.setCantidad(this.inputCantidad.getText().toUpperCase());       // esta variable a guarda los que se ingrese en el input de Cantidad
        
        if(!StringUtils.isEmptyOrWhitespaceOnly(labelId.getText())) {
            elemento.setId(labelId.getText());
        }
        
        inventarioDao dao = new inventarioDao();
        dao.guardar(elemento);
        
        actualizarOutput();                          // actualiza la lista para mostrar elementos nuevos agregados
        
        JOptionPane.showMessageDialog(rootPane, "El Item se Guardo Correctamente");  //mensaje de alerta al guardar
        limpiarInputs();                             /// llamada a la funcion que limpia los inputs
        

        
    }//GEN-LAST:event_btnGuardarActionPerformed

    
//---------------------FUNCION BOTON ELIMINAR----------------------------------//
    
    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        
        int indice = this.outputList.getSelectedIndex();     // permite obtener el numero del indice del elemento en el output y guardarlo como una variable indice
        Lista elemento = lista.get(indice);
        inventarioDao dao = new inventarioDao();
        dao.eliminar(elemento.getId());
        actualizarOutput();                                      // funcion de actualizar la lista para ver los cambios
        
        JOptionPane.showMessageDialog(rootPane, "Se Elimino Correctamente");  //mensaje de alerta al Eliminar
    }//GEN-LAST:event_btnEliminarActionPerformed

    
//---------------------FUNCION MOSTRAR EN VENTANA AL INICIAR----------------------------------//      
    
    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        actualizarOutput();
    }//GEN-LAST:event_formComponentShown

    
//---------------------FUNCION BOTON EDITAR----------------------------------//    
    
    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
       int indice = this.outputList.getSelectedIndex(); 
       Lista elemento = lista.get(indice);
       
       this.inputCodigo.setText(elemento.getCodigo());
       this.inputProducto.setText(elemento.getProducto());
       this.inputMarca.setText(elemento.getMarca());
       this.inputDescripcion.setText(elemento.getDescripcion());
       this.inputUbicacion.setText(elemento.getUbicacion());
       this.inputCantidad.setText(elemento.getCantidad());
       this.labelId.setText(elemento.getId());
    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoActionPerformed
        limpiarInputs();
    }//GEN-LAST:event_btnNuevoActionPerformed


   
//---------------------FUNCION LIMPIAR INPUTS----------------------------------//

    private void limpiarInputs() {
        this.inputCodigo.setText("");
        this.inputProducto.setText("");
        this.inputMarca.setText("");
        this.inputDescripcion.setText("");
        this.inputUbicacion.setText("");
        this.inputCantidad.setText("");
        this.labelId.setText("");
        
    }
    

//---------------------FUNCION ACTUALIZAR LISTA OUTPUT----------------------------------//
    
    private void actualizarOutput() {
        inventarioDao dao = new inventarioDao();
        lista = dao.listar();
        DefaultListModel datos = new DefaultListModel();
        for (int i = 0; i < lista.size(); i++) {          //for para recorrer los la lista e iterar sobre los items en ella
            Lista elemento = lista.get(i);              // toma todos los datos agregados como elementos
            datos.addElement(elemento.getItemCompleto());     // toma todos los datos y los agrega al elemento
        }
        this.outputList.setModel(datos);             //muestra los elementos guardados en datos en el output
    }
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Aplicacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Aplicacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Aplicacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Aplicacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Aplicacion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnNuevo;
    private javax.swing.JTextField inputCantidad;
    private javax.swing.JTextField inputCodigo;
    private javax.swing.JTextField inputDescripcion;
    private javax.swing.JTextField inputMarca;
    private javax.swing.JTextField inputProducto;
    private javax.swing.JTextField inputUbicacion;
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JLabel labelCantidad;
    private javax.swing.JLabel labelCodigo;
    private javax.swing.JLabel labelDescripcion;
    private javax.swing.JLabel labelId;
    private javax.swing.JLabel labelInventario;
    private javax.swing.JLabel labelMarca;
    private javax.swing.JLabel labelProducto;
    private javax.swing.JLabel labelUbicacion;
    private javax.swing.JList<String> outputList;
    // End of variables declaration//GEN-END:variables
}
